[tool.poetry]
name = "macchina"
version = "0.1.0"
description = ""
authors = ["gorjanradevski <gorjanradevski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.3"
torchvision = "^0.4.2"
jupyter = "^1.0"
transformers = "^2.1"
tqdm = "^4.39"
Pillow = "^6.2"
scikit-learn = "^0.21.3"
matplotlib = "=3.0.2"
ndjson = "^0.2.0"
natsort = "^6.2"
opencv-python = "^4.1"
nltk = "^3.4"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = {version = "^3.7", allows-prereleases = true}
pytest = "^5.3"
google_images_download = "^2.8"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
